FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl sudo
RUN sudo apt-get install -y nodejs npm
RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]