version: '3.7'

services:

  swarm-mongo-db:
    image: mongo
    networks:
      - backend
    volumes:
      - dbdata:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # swarm-mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - swarm-mongo-db
  #   networks:
  #     - backend
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #     ME_CONFIG_MONGODB_SERVER: swarm-mongo-db

volumes:
  dbdata:
    driver: local

networks:
  frontend:
  backend: